stages:
  - build
  - test
  - deploy

deploy-gamehighlights-frontend:
  stage: deploy
  script:
    - docker build . -t "$CI_REGISTRY_IMAGE_PREFIX/game-highlights-vue:$CI_COMMIT_REF_SLUG" -t "$CI_REGISTRY_IMAGE_PREFIX/family-planner:latest"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push --all-tags "$CI_REGISTRY_IMAGE_PREFIX/game-highlights-vue"
  only:
    - master
build-gamehighlights-frontend:
  stage: build
  script:
   - yarn install
   - yarn run build
test-gamehighlights-frontend:
  stage: test
  script:
   - yarn install
   - yarn run test
